
package trng.imcs.soap.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "LoanEligibilityService", targetNamespace = "http://www.example.org/LoanService/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface LoanEligibilityService {


    /**
     * 
     * @param parameters
     * @return
     *     returns trng.imcs.soap.client.LoanResponse
     */
    @WebMethod(action = "http://www.example.org/LoanService/testEligibility")
    @WebResult(name = "LoanResponse", targetNamespace = "http://www.example.org/LoanResponse", partName = "parameters")
    public LoanResponse testEligibility(
        @WebParam(name = "LoanRequest", targetNamespace = "http://www.example.org/LoanRequest", partName = "parameters")
        LoanRequest parameters);

}
