
package trng.imcs.soap.client;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "ServiceImplService", targetNamespace = "http://soap.imcs.trng/", wsdlLocation = "http://localhost:9090/LoanWS/loanService?wsdl")
public class ServiceImplService
    extends Service
{

    private final static URL SERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(trng.imcs.soap.client.ServiceImplService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = trng.imcs.soap.client.ServiceImplService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:9090/LoanWS/loanService?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:9090/LoanWS/loanService?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        SERVICEIMPLSERVICE_WSDL_LOCATION = url;
    }

    public ServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServiceImplService() {
        super(SERVICEIMPLSERVICE_WSDL_LOCATION, new QName("http://soap.imcs.trng/", "ServiceImplService"));
    }

    /**
     * 
     * @return
     *     returns LoanEligibilityService
     */
    @WebEndpoint(name = "ServiceImplPort")
    public LoanEligibilityService getServiceImplPort() {
        return super.getPort(new QName("http://soap.imcs.trng/", "ServiceImplPort"), LoanEligibilityService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LoanEligibilityService
     */
    @WebEndpoint(name = "ServiceImplPort")
    public LoanEligibilityService getServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap.imcs.trng/", "ServiceImplPort"), LoanEligibilityService.class, features);
    }

}
